# Generated by Django 5.1.4 on 2024-12-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_u', '0007_emailverificationotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationOTP',
        ),
    ]
