# Generated by Django 5.1.4 on 2024-12-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_u', '0008_delete_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
