# Generated by Django 5.1.4 on 2024-12-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_u', '0013_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_url',
            new_name='profile',
        ),
    ]
