# Generated by Django 5.1.4 on 2024-12-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_u', '0014_rename_avatar_url_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='profile_picture',
        ),
    ]
